checksumBehavior: throw

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmAlwaysAuth: false

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: false
  "https://registry.npmjs.org":
    npmAlwaysAuth: false
  "https://registry.yarnpkg.com":
    npmAlwaysAuth: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js
